name: Pull Request

description: File a standard PR for the Parsons project

body:
  - type: textarea
    id: what-is-change
    attributes:
      label: What is this change?
      description: List out each change and link to any relevant Github issues or Slack discussion.
      placeholder: |
        - List changes here
    validations:
      required: true

  - type: textarea
    id: considerations
    attributes:
      label: Considerations for discussion
      description: List out any significant design decisions that were made and why.
      placeholder: |
        - List decisions / needed discussion here
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: How to test the changes (if needed)
      description: How should a reviewer test this functionality?
      placeholder: |
        - List testing steps here
    validations:
      required: false

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: |
        Breaking changes are changes to our public API which may require existing users to change their code.
        If there are no breaking changes, any existing parsons user should not need to do anything after updating their parsons version.
      options:
        - "Non-breaking change — This PR does not introduce breaking changes."
        - "Breaking change — This PR introduces one or more breaking changes."
    validations:
      required: true

  - type: textarea
    id: breaking-details
    attributes:
      label: Breaking Change Details (if needed)
      description: List out any changes to the API that may cause breaks for developer implementation.
      placeholder: |
        - List breaking changes here
    validations:
      required: false
