name: Post coverage comment

on:
    workflow_run:
        workflows: ["Python checks"]
        types:
            - completed

permissions:
    contents: read

jobs:
    test:
        name: Run tests & display coverage

        runs-on: ubuntu-latest
        if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'

        permissions:
            pull-requests: write
            contents: write
            actions: read

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481  # v2.11.0
              with:
                  egress-policy: audit

            # DO NOT run actions/checkout here, for security reasons
            # For details, refer to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

            - name: Post comment
              uses: py-cov-action/python-coverage-comment-action@d1ff8fbb5ff80feedb3faa0f6d7b424f417ad0e1  # v3.30
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}