name: Build & Publish Wheels + Source

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: "3.13"
          cache: pip

      - uses: install-pinned/uv@b9511b633710c8bbe8ba48376771dba624746799

      - run: |
          uv pip install --system -r requirements-dev.txt
          uv pip install --system -e .[all]

      - run: |
          python setup.py check

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          python -m build --sdist --outdir wheels parsons

      - run: git pull && python -m cibuildwheel parsons/ --output-dir wheels

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: wheels-${{ matrix.os }}
          path: wheels

  publish_wheels:
    if: github.repository_owner == 'move-coop'
    needs: build_wheels

    runs-on: ubuntu-latest
    environment: release

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          verify-metadata: true
          skip-existing: true
          packages-dir: wheels
          verbose: true
