# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Scorecard supply-chain security

on:
    branch_protection_rule: null
    schedule:
        - cron: '20 7 * * 2'
    push:
        branches:
            - 'main'
            - 'major-release'
    pull_request:
        branches:
            - 'main'
            - 'major-release'

permissions: read-all

jobs:
    analysis:
        name: Scorecard analysis
        runs-on: ubuntu-latest
        permissions:
            security-events: write
            id-token: write

        steps:
            - name: Harden runner
              uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
              with:
                  egress-policy: audit

            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  persist-credentials: false

            - name: Run analysis
              uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
              with:
                  results_file: results.sarif
                  results_format: sarif
                  publish_results: true

            - name: Upload to code-scanning
              uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
              with:
                  sarif_file: results.sarif
